version: "3"

services:
  console:
    build:
      context: .
      args:
        NODE_ENV: "development"
    entrypoint: bash
    volumes:
      - ./:/app

  server:
    build:
      context: .
      args:
        NODE_ENV: "development"
    command: gatsby develop -H 0.0.0.0
    ports:
      - "8000:8000"
    entrypoint: bash
    volumes:
      - ./:/app

