version: "3"

services:
  console:
    build:
      context: .
    environment:
      - NODE_ENV=development
    ports:
      - 8000:8000
      - 9929:9929
      - 9230:9230
    volumes:
      - /app/node_modules
      - .:/app
